#!/bin/bash

check_prereq() {


# verify existing of ~/xud-simnet
temp=`ls ~/xud-simnet`
if [ $? -ne 0 ]; then
	echo "~/xud-simnet is missing"
	exit 1
fi
# verify git
temp=`which git`
if [ $? -ne 0 ]; then
	echo "git is missing"
	exit 1
fi
# verify make
temp=`which make`
if [ $? -ne 0 ]; then
	echo "make is missing"
	exit 1
fi
# verify npm
temp=`which npm`
if [ $? -ne 0 ]; then
	echo "npm is missing"
	exit 1
fi
# verify python
temp=`which python`
if [ $? -ne 0 ]; then
	echo "python is missing"
	exit 1
fi
if ! command -v python3.7
 then
   echo "python3.7 is missing"
   exit 1
fi
# verify killall
temp=`which killall`
if [ $? -ne 0 ]; then
	echo "killall is missing"
	exit 1
fi
# verify go
temp=`which go`
if [ $? -ne 0 ]; then
	echo "go is missing"
	exit 1
fi
# verify PATH
temp=`echo $PATH|grep xud-simnet/scripts`
if [ $? -ne 0 ]; then
	echo "PATH is not properly set. Did you source setup.bash?"
	exit 1
fi
# verify PATH
temp=`echo $PATH|grep xud-simnet/go/bin`
if [ $? -ne 0 ]; then
	echo "PATH is not properly set. Did you source setup.bash?"
	exit 1
fi
echo "found all pre-requisites"
}


make_dir () {
if ! mkdir "$1"; then
	echo "$1 already exists. Please run xud-simnet-clean to clean all leftovers before installing."
	exit 1
fi
}

if ! cd ~/xud-simnet; then
  	  echo "~/xud-simnet is missing"
	exit 1
fi	

source setup.bash
check_prereq
#make_dir ~/xud-simnet/btcd
make_dir ~/xud-simnet/ltcd
make_dir ~/xud-simnet/lndbtc
make_dir ~/xud-simnet/lndltc
make_dir ~/xud-simnet/xud-wd

##### glide
#if ! go get -u github.com/Masterminds/glide > /tmp/xud-simnet-install.log 2>&1; then
#	echo "unable to install glide"
#	exit 1
#fi 
#echo "glide installed"

#### ltcd
if ! git clone https://github.com/ltcsuite/ltcd.git $GOPATH/src/github.com/ltcsuite/ltcd >> /tmp/xud-simnet-install.log 2>&1; then
	echo "unable to git clone ltcd"
	exit 1
fi
cd $GOPATH/src/github.com/ltcsuite/ltcd
echo "ltcd repo downloaded"
if ! git apply ~/xud-simnet/scripts/ltcd.patch >> /tmp/xud-simnet-install.log 2>&1 ; then
	echo "unable to apply ltcd pacth"
	exit 1
fi
echo "ltcd patched"
if ! GO111MODULE=on go install -v . ./cmd/...  >> /tmp/xud-simnet-install.log 2>&1; then
	echo "unable to go instll ltcd"
	exit 1
fi  
 
echo "ltcd installed"
#### btcd
#if ! git clone https://github.com/btcsuite/btcd.git $GOPATH/src/github.com/btcsuite/btcd >> /tmp/xud-simnet-install.log 2>&1; then
#	echo "unable to git clone btcd"
#	exit 1
#fi
#cd $GOPATH/src/github.com/btcsuite/btcd
#echo "btcd repo downloaded"
#if ! git apply ~/xud-simnet/scripts/btcd.patch >> /tmp/xud-simnet-install.log 2>&1 ; then
#	echo "unable to apply btcd pacth"
#	exit 1
#fi
#echo "btcd patched"
#if ! GO111MODULE=on go install -v . ./cmd/...  >> /tmp/xud-simnet-install.log 2>&1 ; then
#	echo "unable to go instll btcd"
#	exit 1
#fi  
#echo "btcd installed"

#### lnd
cd /tmp
rm -rf lnd
mkdir lnd
cd lnd
cp ~/xud-simnet/lnd-v0.7.1-beta/*.tar.gz .
tar -xzf vendor.tar.gz
tar -xzf lnd-source-v0.7.1-beta.tar.gz
	
git apply ~/xud-simnet/scripts/limits.patch
echo "lnd limits patched"

cd /tmp/lnd/vendor/github.com/lightninglabs/neutrino

chmod +w blockmanager.go
if ! patch  <~/xud-simnet/scripts/neutrino.patch ; then
        echo "unable to patch neutrion"
        exit 1
fi
echo "neutrino patched"

sed -i.bak "s/\!w.isDevEnv/w.isDevEnv/" /tmp/lnd/vendor/github.com/btcsuite/btcwallet/wallet/wallet.go 

cd /tmp/lnd


if ! GO111MODULE=on go install -v -mod=vendor -tags="invoicesrpc" -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.7.1-beta" ./cmd/lnd >> /tmp/xud-simnet-install.log 2>&1 ; then
	echo "unable to compile lnd"
	exit 1
fi

if ! GO111MODULE=on go install -v -mod=vendor -tags="invoicesrpc" -ldflags "-X github.com/lightningnetwork/lnd/build.Commit=v0.7.1-beta" ./cmd/lncli >> /tmp/xud-simnet-install.log 2>&1 ; then
	echo "unable to compile lnd"
	exit 1
fi

echo "lnd installed"
#### xud
cd ~/xud-simnet
if ! git clone https://github.com/ExchangeUnion/xud.git >> /tmp/xud-simnet-install.log 2>&1; then
	echo "unable to git clone xud"
	exit 1
fi
cd xud
if ! npm install >> /tmp/xud-simnet-install.log 2>&1 ; then
	echo "unable to npm install xud"
	exit 1
fi
if ! npm run compile >> /tmp/xud-simnet-install.log 2>&1 ; then
	echo "unable to build xud"
	exit 1
fi
~/xud-simnet/scripts/xud-simnet-install-raiden
echo "xud installed"
echo "Ready!"
