#!/bin/bash

delete_dir() {
	if ! rm -rf  $1 >/dev/null 2>&1; then
		echo "unable to delete directory $1"
		exit 1
	fi
	return 0
}

if ! cd ~/xud-simnet; then
          echo "~/xud-simnet is missing"
        exit 1
fi

source setup.bash

read -p "Are you sure (y/n)? " -n 1 -r
echo     
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
	exit 1
fi

#confirm_all_not_running
xud-simnet-stop

delete_dir "btcd"
delete_dir "ltcd"
delete_dir "lndbtc"
delete_dir "lndltc"
delete_dir "xud"
delete_dir "xud-wd"
#delete_dir "raiden-wd"
delete_dir "go"
echo "Done. You can now use xud-simnet-install"


