#!/bin/bash

cd ~/xud-simnet

shopt -s expand_aliases
source setup.bash

echo "stopping all processes"

btcctl stop >/dev/null 2>&1
ltcctl stop >/dev/null 2>&1
sleep 5 

kill $(ps aux | egrep 'node.*lndbtc'|awk '{print $2}') >/dev/null 2>&1
killall lnd >/dev/null 2>&1
killall btcd >/dev/null 2>&1
killall ltcd >/dev/null 2>&1

kill -9 $(ps aux | egrep 'node.*lndbtc'|awk '{print $2}') >/dev/null 2>&1
killall -9 lnd >/dev/null 2>&1
killall -9 btcd >/dev/null 2>&1
killall -9 ltcd >/dev/null 2>&1


confirm_all_not_running
echo "Done"
