#!/bin/bash

cd ~/xud-simnet

shopt -s expand_aliases
source setup.bash

pairs=`xucli listpairs --json|grep "/" |wc -l`

if [ $pairs -eq 4 ] ; then
	exit 1
fi

WETH=0x892F91dc428Fc3Dc0a57eC46C8245F2511b8a542
DAI=0x4115652c9025d99512e9026B8F11C3E265bfecD7

xucli removepair WETH/BTC > /dev/null 2>&1
xucli removepair BTC/DAI > /dev/null 2>&1
xucli removepair LTC/DAI > /dev/null 2>&1

xucli removecurrency WETH > /dev/null 2>&1
xucli removecurrency DAI > /dev/null 2>&1

xucli addcurrency WETH Raiden 18 $WETH > /dev/null 2>&1
xucli addcurrency DAI Raiden 18 $DAI > /dev/null 2>&1

xucli addpair WETH BTC > /dev/null 2>&1
xucli addpair BTC DAI > /dev/null 2>&1
xucli addpair LTC DAI > /dev/null 2>&1

xucli listpairs

