#!/bin/bash

cd ~/xud-simnet

shopt -s expand_aliases
source setup.bash

echo "stopping all processes"

btcctl stop >/dev/null 2>&1
ltcctl stop >/dev/null 2>&1
sleep 5 

kill $(ps aux | egrep 'node.*lndbtc|node.*lnd.BTC'|awk '{print $2}') >/dev/null 2>&1
kill $(ps aux|egrep 'Python.*raiden.*4321.*8546'|awk '{print $2}') >/dev/null 2>&1
killall lnd >/dev/null 2>&1
killall raiden >/dev/null 2>&1

kill -9 $(ps aux | egrep 'node.*lndbtc|node.*lnd.BTC'|awk '{print $2}') >/dev/null 2>&1
kill -9 $(ps aux|egrep 'Python.*raiden.*4321.*8546'|awk '{print $2}') >/dev/null 2>&1
killall -9 lnd >/dev/null 2>&1
killall -9 raiden >/dev/null 2>&1


confirm_all_not_running
echo "Done"
