#!/bin/bash

cd ~/xud-simnet

shopt -s expand_aliases
source setup.bash

pairs=`xucli listpairs --json|grep "/" |wc -l`

if [ $pairs -eq 4 ] ; then
	exit 1
fi

WETH="0x46AF55C4320D37bCeA9a3cF6f0Fe18FFf7D9685b"
DAI="0x7CB0a7b39358CFac898CD26A6934c2f74d9aAD20"

xucli removepair WETH/BTC > /dev/null 2>&1
xucli removepair BTC/DAI > /dev/null 2>&1
xucli removepair LTC/DAI > /dev/null 2>&1

xucli removecurrency WETH > /dev/null 2>&1
xucli removecurrency DAI > /dev/null 2>&1

xucli addcurrency WETH Raiden 18 $WETH > /dev/null 2>&1
xucli addcurrency DAI Raiden 18 $DAI > /dev/null 2>&1

xucli addpair WETH BTC > /dev/null 2>&1
xucli addpair BTC DAI > /dev/null 2>&1
xucli addpair LTC DAI > /dev/null 2>&1

xucli listpairs

