#!/bin/bash


gitit(){
git fetch > /dev/null 2>&1
status=`git status 2>&1`
uptodate=`echo -n "${status}" 2> /dev/null | egrep "Your branch is up( |-)to( |-)date" &> /dev/null; echo "$?"`
if [ "${uptodate}" -eq "0" ]; then
        return 0
fi
git reset --hard
if [ $? -ne 0 ]; then
        msg="git reset failed"
        echo $msg
        return 1
fi
git pull
if [ $? -ne 0 ]; then
        msg="git pull failed"
        echo $msg
        return 1
fi
npm install
if [ $? -ne 0 ]; then
        msg="npm install failed"
        echo $msg
        return 1
fi
npm run compile
if [ $? -ne 0 ]; then
        msg="XUD compile failed"
        echo $msg
        return 1
fi
status=`git status 2>&1`
uptodate=`echo -n "${status}" 2> /dev/null | egrep "Your branch is up( |-)to( |-)date" &> /dev/null; echo "$?"`
if [ "${uptodate}" -ne "0" ]; then
        msg="update FAILED!!!"
        echo $msg
        return 1
fi
msg="XUD project updated. Project is up to date now"
echo "$msg"
return 0
}


cd ~/xud-simnet
shopt -s expand_aliases
source setup.bash

confirm_all_not_running

cd xud
gitit 
if [ $? -ne 0 ]; then
	return 1
fi
cd ..
	
echo "starting all processes"
xname=`hostname`
xname=${xname:0:28}
timeout="120"
#### btcd
cd ~/xud-simnet/btcd
nohup btcd -C ./btcd.conf --simnet --txindex --datadir=./data --logdir=./logs --addpeer=35.231.222.142:18555 --rpcuser=xu --rpcpass=xu  --rpclisten 127.0.0.1:18556 --nolisten --rpccert=./rpc.cert --rpckey=./rpc.key> /dev/null 2>&1 &
num="0"
while true; do
	if (("$num" > "$timeout"))
	then
		echo "btcd didn't start properly"
		exit 1
	fi
	if  btcctl getinfo 2>&1 |  grep blocks > /dev/null 2>&1; then
		break	
	fi
	sleep 1
	num=$[$num + 1]
done
echo "btcd started"
#### ltcd
cd ~/xud-simnet/ltcd
nohup ltcd -C ./btcd.conf --simnet --txindex --datadir=./data --logdir=./logs --addpeer=35.231.222.142:19555 --rpcuser=xu --rpcpass=xu --rpclisten=127.0.0.1:19556 --nolisten --rpccert=./rpc.cert --rpckey=./rpc.key> /dev/null 2>&1 &
num="0"
while true; do
	if (("$num" > "$timeout"))
	then
		echo "ltcd didn't start properly"
		exit 1
	fi
	if  ltcctl getinfo 2>&1 |  grep blocks > /dev/null 2>&1; then
		break	
	fi
	sleep 1
	num=$[$num + 1]
done
echo "ltcd started"
#### lndbtc
cd ~/xud-simnet/lndbtc
cert=~/xud-simnet/btcd/rpc.cert
nohup lnd --noseedbackup --rpclisten=127.0.0.1:10002 --listen=127.0.0.1:10012 --restlisten=8002 --datadir=./data --logdir=./logs  --nobootstrap --no-macaroons --bitcoin.active --bitcoin.simnet  --btcd.rpcuser=xu --btcd.rpcpass=xu --debuglevel=debug --alias="BTC@$xname" --btcd.rpchost=127.0.0.1:18556  --btcd.rpccert=$cert > /dev/null 2>&1 &
num="0"
while true; do
	if (("$num" > "$timeout"))
	then
		echo "lndbtc didn't start properly"
		exit 1
	fi
	if  lndbtc-lncli getinfo 2>&1 |  grep block > /dev/null 2>&1; then
		break	
	fi
	sleep 1
	num=$[$num + 1]
done
echo "lndbtc started"
#### lndltc
cd ~/xud-simnet/lndltc
cert=~/xud-simnet/ltcd/rpc.cert
nohup lnd --noseedbackup --rpclisten=127.0.0.1:10001 --listen=127.0.0.1:10011 --restlisten=8001 --datadir=./data --logdir=./logs  --nobootstrap --no-macaroons --litecoin.active --litecoin.simnet  --ltcd.rpcuser=xu --ltcd.rpcpass=xu --debuglevel=debug --alias="LTC@$xname" --ltcd.rpchost=127.0.0.1:19556  --ltcd.rpccert=$cert > /dev/null 2>&1 &
num="0"
while true; do
	if (("$num" > "$timeout"))
	then
		echo "lndltc didn't start properly"
		exit 1
	fi
	if  lndltc-lncli getinfo 2>&1 |  grep block > /dev/null 2>&1; then
		break	
	fi
	sleep 1
	num=$[$num + 1]
done
echo "lndltc started"
#### Starting xud
cd ~/xud-simnet/xud-wd
#nohup xud --raiden.disable --lndbtc.nomacaroons --lndbtc.port 10002 --lndltc.nomacaroons --lndltc.port 10001 -x . > /dev/null 2>&1 &
nohup xud --raiden.disable --lnd.BTC.nomacaroons --lnd.BTC.port 10002 --lnd.LTC.nomacaroons --lnd.LTC.port 10001 -x . > /dev/null 2>&1 &
num="0"
while true; do
	if (("$num" > "$timeout"))
	then
		echo "xud didn't start properly"
		exit 1
	fi
	if  xucli getinfo 2>&1 |  grep block > /dev/null 2>&1; then
		break	
	fi
	sleep 1
	num=$[$num + 1]
done
echo "xud started"

#check lndbtc synced
echo  "sync lndbtc to chain"
while true; do
	echo -n "."
	if  lndbtc-lncli getinfo 2>&1 |grep synced_to_chain.*true  > /dev/null 2>&1; then
		break	
	fi
	sleep 1
done
echo -e "\nlndbtc synced to chain"

#check lndltc synced
echo  "sync lndltc to chain"
while true; do
	echo -n "."
	if  lndltc-lncli getinfo 2>&1 |grep synced_to_chain.*true  > /dev/null 2>&1; then
		break	
	fi
	sleep 1
done
echo -e "\nlndltc synced to chain"

num="0"
while true; do
	if (("$num" > "$timeout"))
	then
		echo "xud didn't start properly. No litecoin support"
		exit 1
	fi
	if  xucli getinfo 2>&1 |  grep litecoin > /dev/null 2>&1; then
		break	
	fi
	sleep 1
	num=$[$num + 1]
done
num="0"
while true; do
	if (("$num" > "$timeout"))
	then
		echo "xud didn't start properly. No bitcoin support"
		exit 1
	fi
	if  xucli getinfo 2>&1 |  grep bitcoin > /dev/null 2>&1; then
		break	
	fi
	sleep 1
	num=$[$num + 1]
done

echo "Ready!"
