#!/bin/bash

cd ~/xud-simnet
shopt -s expand_aliases
source setup.bash

activate_venv

EndpointRegistry="0xF6Ac1fE0421036e1f2DB6cC23CC2cFc36288d434"
SecretRegistry="0x9B16762c9f6390a19208bDE8bd8AEc81D7C6BDaB"
TokenNetworkRegistry="0x07679899f46422A2a9e5A3502815131Fe6d0dd0a"
env="production"

address_file=~/xud-simnet/raiden-wd/address
if [ ! -f $address_file ]; then
	echo "raiden was not properlly installed"
	exit 1
fi
tail -1 $address_file
address=`grep "Address" $address_file |cut -d " " -f 2`
passwd_file=~/xud-simnet/raiden-wd/passwd_file
datadir=~/xud-simnet/raiden-wd/exchange
keystore=~/xud-simnet/raiden-wd/keystore

cd  ~/xud-simnet/raiden-wd
raiden --datadir $datadir --keystore-path $keystore  --network-id 4321 --accept-disclaimer --address $address --rpc --api-address 0.0.0.0:5001 --environment-type $env  --password-file $passwd_file --no-sync-check --accept-disclaimer --tokennetwork-registry-contract-address $TokenNetworkRegistry --secret-registry-contract-address $SecretRegistry --endpoint-registry-contract-address $EndpointRegistry --gas-price 10000000000 --eth-rpc-endpoint 35.231.222.142:8546  --matrix-server https://raidentransport.exchangeunion.com

deactivate
